export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const NAME_OF_PAGE = 'NAME_OF_PAGE';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const ADD__MENU_LINK = 'ADD__MENU_LINK';
export const UPDATE__MENU_LINK = 'UPDATE__MENU_LINK';
export const GET_ALL__MENU_LINK = 'GET_ALL__MENU_LINK';
export const GET_ONE__MENU_LINK = 'GET_ONE__MENU_LINK';
export const DELETE__MENU_LINK = 'DELETE__MENU_LINK';
export const ADD__GROUP_OF_MENU_LINK = 'ADD__GROUP_OF_MENU_LINK';
export const UPDATE__GROUP_OF_MENU_LINK = 'UPDATE__GROUP_OF_MENU_LINK';
export const GET_ALL__GROUP_OF_MENU_LINK = 'GET_ALL__GROUP_OF_MENU_LINK';
export const GET_ONE__GROUP_OF_MENU_LINK = 'GET_ONE__GROUP_OF_MENU_LINK';
export const DELETE__GROUP_OF_MENU_LINK = 'DELETE__GROUP_OF_MENU_LINK';
