export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const NAME_OF_PAGE = 'NAME_OF_PAGE';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const ADD__MENU_LINK = 'ADD__MENU_LINK';
export const UPDATE__MENU_LINK = 'UPDATE__MENU_LINK';
export const GET_ALL__MENU_LINK = 'GET_ALL__MENU_LINK';
export const GET_ONE__MENU_LINK = 'GET_ONE__MENU_LINK';
export const DELETE__MENU_LINK = 'DELETE__MENU_LINK';

export const ADD__GROUP_OF_MENU_LINK = 'ADD__GROUP_OF_MENU_LINK';
export const UPDATE__GROUP_OF_MENU_LINK = 'UPDATE__GROUP_OF_MENU_LINK';
export const GET_ALL__GROUP_OF_MENU_LINK = 'GET_ALL__GROUP_OF_MENU_LINK';
export const GET_ONE__GROUP_OF_MENU_LINK = 'GET_ONE__GROUP_OF_MENU_LINK';
export const DELETE__GROUP_OF_MENU_LINK = 'DELETE__GROUP_OF_MENU_LINK';

export const ADD__OUR_USER = 'ADD__OUR_USER';
export const UPDATE__OUR_USER = 'UPDATE__OUR_USER';
export const GET_ALL__OUR_USER = 'GET_ALL__OUR_USER';
export const GET_ONE__OUR_USER = 'GET_ONE__OUR_USER';
export const DELETE__OUR_USER = 'DELETE__OUR_USER';

export const ADD__WORKER = 'ADD__WORKER';
export const UPDATE__WORKER = 'UPDATE__WORKER';
export const GET_ALL__WORKER = 'GET_ALL__WORKER';
export const GET_ONE__WORKER = 'GET_ONE__WORKER';
export const DELETE__WORKER = 'DELETE__WORKER';

export const ADD__UNIT = 'ADD__UNIT';
export const UPDATE__UNIT = 'UPDATE__UNIT';
export const GET_ALL__UNIT = 'GET_ALL__UNIT';
export const GET_ONE__UNIT = 'GET_ONE__UNIT';
export const DELETE__UNIT = 'DELETE__UNIT';

export const ADD__TYPE_FIRM = 'ADD__TYPE_FIRM';
export const UPDATE__TYPE_FIRM = 'UPDATE__TYPE_FIRM';
export const GET_ALL__TYPE_FIRM = 'GET_ALL__TYPE_FIRM';
export const GET_ONE__TYPE_FIRM = 'GET_ONE__TYPE_FIRM';
export const DELETE__TYPE_FIRM = 'DELETE__TYPE_FIRM';

export const ADD__SERVICE_JOB = 'ADD__SERVICE_JOB';
export const UPDATE__SERVICE_JOB = 'UPDATE__SERVICE_JOB';
export const GET_ALL__SERVICE_JOB = 'GET_ALL__SERVICE_JOB';
export const GET_ONE__SERVICE_JOB = 'GET_ONE__SERVICE_JOB';
export const DELETE__SERVICE_JOB = 'DELETE__SERVICE_JOB';

export const ADD__PRODUCT = 'ADD__PRODUCT';
export const UPDATE__PRODUCT = 'UPDATE__PRODUCT';
export const GET_ALL__PRODUCT = 'GET_ALL__PRODUCT';
export const GET_ONE__PRODUCT = 'GET_ONE__PRODUCT';
export const DELETE__PRODUCT = 'DELETE__PRODUCT';

export const ADD__GROUP_SERVICE_JOB = 'ADD__GROUP_SERVICE_JOB';
export const UPDATE__GROUP_SERVICE_JOB = 'UPDATE__GROUP_SERVICE_JOB';
export const GET_ALL__GROUP_SERVICE_JOB = 'GET_ALL__GROUP_SERVICE_JOB';
export const GET_ONE__GROUP_SERVICE_JOB = 'GET_ONE__GROUP_SERVICE_JOB';
export const DELETE__GROUP_SERVICE_JOB = 'DELETE__GROUP_SERVICE_JOB';

export const ADD__GROUP_PRODUCT = 'ADD__GROUP_PRODUCT';
export const UPDATE__GROUP_PRODUCT = 'UPDATE__GROUP_PRODUCT';
export const GET_ALL__GROUP_PRODUCT = 'GET_ALL__GROUP_PRODUCT';
export const GET_ONE__GROUP_PRODUCT = 'GET_ONE__GROUP_PRODUCT';
export const DELETE__GROUP_PRODUCT = 'DELETE__GROUP_PRODUCT';

export const ADD__GROUP_EXPENSE = 'ADD__GROUP_EXPENSE';
export const UPDATE__GROUP_EXPENSE = 'UPDATE__GROUP_EXPENSE';
export const GET_ALL__GROUP_EXPENSE = 'GET_ALL__GROUP_EXPENSE';
export const GET_ONE__GROUP_EXPENSE = 'GET_ONE__GROUP_EXPENSE';
export const DELETE__GROUP_EXPENSE = 'DELETE__GROUP_EXPENSE';

export const ADD__FIRM = 'ADD__FIRM';
export const UPDATE__FIRM = 'UPDATE__FIRM';
export const GET_ALL__FIRM = 'GET_ALL__FIRM';
export const GET_ONE__FIRM = 'GET_ONE__FIRM';
export const DELETE__FIRM = 'DELETE__FIRM';

export const ADD__EXPENSE = 'ADD__EXPENSE';
export const UPDATE__EXPENSE = 'UPDATE__EXPENSE';
export const GET_ALL__EXPENSE = 'GET_ALL__EXPENSE';
export const GET_ONE__EXPENSE = 'GET_ONE__EXPENSE';
export const DELETE__EXPENSE = 'DELETE__EXPENSE';

export const ADD__OUR_NAKL = 'ADD__OUR_NAKL';
export const UPDATE__OUR_NAKL = 'UPDATE__OUR_NAKL';
export const GET_ALL__OUR_NAKL = 'GET_ALL__OUR_NAKL';
export const GET_ONE__OUR_NAKL = 'GET_ONE__OUR_NAKL';
export const DELETE__OUR_NAKL = 'DELETE__OUR_NAKL';

export const ADD__OUR_INVOICE = 'ADD__OUR_INVOICE';
export const UPDATE__OUR_INVOICE = 'UPDATE__OUR_INVOICE';
export const GET_ALL__OUR_INVOICE = 'GET_ALL__OUR_INVOICE';
export const GET_ONE__OUR_INVOICE = 'GET_ONE__OUR_INVOICE';
export const DELETE__OUR_INVOICE = 'DELETE__OUR_INVOICE';

export const ADD__OUR_ACT = 'ADD__OUR_ACT';
export const UPDATE__OUR_ACT = 'UPDATE__OUR_ACT';
export const GET_ALL__OUR_ACT = 'GET_ALL__OUR_ACT';
export const GET_ONE__OUR_ACT = 'GET_ONE__OUR_ACT';
export const DELETE__OUR_ACT = 'DELETE__OUR_ACT';

export const ADD__CONTRACT = 'ADD__CONTRACT';
export const UPDATE__CONTRACT = 'UPDATE__CONTRACT';
export const GET_ALL__CONTRACT = 'GET_ALL__CONTRACT';
export const GET_ONE__CONTRACT = 'GET_ONE__CONTRACT';
export const DELETE__CONTRACT = 'DELETE__CONTRACT';
